server:
  port: 8084

spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.pranit: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"